dependency-check/dependency-check-gradle

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/CheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy
exposing the hints file feature.  I couldn't find any documentation to update in this project but I did update gradle documentation in the main Dependency Check project.
> adding support for hints file

- README.md
Adding travisCI badge to show build status on readme
> Adding travisCI badge to show build status

- README.md
- src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy
- src/integTest/resources/suppressionFiles.gradle
- src/integTest/resources/suppressions.xml
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Purge.groovy
> Fix suppresionFiles interpolation

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
At the end of the analysis the vulnerabilities have been printed in random order with duplicate entries when a vulnerability has been detected in multiple dependencies.
With this PR the list does not contain duplicates and is in a defined order:
1. CVSS score (desc)
2. Name (asc)
This facilitates comparing the results of different analysis runs.
> Cleanup of output of vulnerabilites at the end of the analysis:

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy
Enhance PR #88 and general code cleanup.
> Enhance Analysis

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Resolves two issues:
1. Supports older versions of gradle (#95)
2. Resolve #94 - continued improvements around Android builds
> Update artifact resolution

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> fix spelling

- src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/CacheExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
> #157 Allow programmatical extension configuration

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/SlackExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/service/SlackNotificationSenderService.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This add's the ability to send a slack notification to a slack webhook, when the dependency analyze fails
> Slack notification functionality on fail

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
> Make non-mandatory configuration non-mandatory

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
a few weeks ago you accepted my pull request, but the slack integration doesn't seem to work. I suspect you had merge conflicts and forgot something. This commit should fix it
> fixed slack integration

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> Add yarn.lock to default scan set

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Fixes https://github.com/dependency-check/dependency-check-gradle/issues/247
> Fix sha256 calculation

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
Resolves #188 - allow non-proxy host to be specified.
> Update Proxy Config

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> Correct Output Directory

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
fix: remove warning on old config, resolves #246
> Remove old warning

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
> fix: cast exception assigning proxyPort

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
> Split the value from the nonProxyHosts-field into a list by the pipe

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/HostedSuppressionsExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
Adds configuration options to customize the settings for the hosted suppressions file to be integrated in DependencyCheck 8.0.0 by PR https://github.com/jeremylong/DependencyCheck/pull/4901
As this is for DependencyCheck 8.0.0 I've also updated odcVersion to it's snapshot
> Add configurability for the new hosted suppressions file

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
jackson-bom caused an endless (recursive) loop - the PR adds checks to ensure we don't cycle down paths already followed.
Resolves https://github.com/dependency-check/dependency-check-gradle/issues/307
> fix: stack overflow

- build.gradle
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- resolves https://github.com/dependency-check/dependency-check-gradle/issues/317
- extends usage of `@groovy.transform.CompileStatic` to resolve bugs
> fix: MalformedPackageException

- .github/workflows/pull_requests.yml
- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
> fix: add collection setter for suppressionFiles

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> fix: make format configuration more flexible

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
> fix: ensure suppressionFiles is non-null

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPluginIntegSpec.groovy
- src/test/resources/aggregateApp.gradle
- src/test/resources/aggregateCore.gradle
- src/test/resources/noSkipTestGroups.gradle
- src/test/resources/outputDir.gradle
- src/test/resources/skipGroups.gradle
- src/test/resources/skipTestGroups.gradle
- src/test/resources/suppressionFiles.gradle
- upgrade to latest ODC
- bump gradle wrapper
- modernize tests for newer version of gradle
> fix: resolve build failures

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
see https://github.com/dependency-check/dependency-check-gradle/issues/339\#issuecomment-1609649834
> fix: remove transient modifier

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This allows to set the `kev.check.validforhours` parameter via Gradle
> fix: add configuration parameter for `kev.check.validforhours`

- README.md
> docs: document build environment

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/DataExtension.groovy
- src/main/resources/task.properties
- src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
> fix: correct 9.x data directory

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
> fix: add pnpm-lock.yaml to default scan set

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/NodeAuditExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
> fix: expose analyzer.node.audit.url

- src/main/groovy/org/owasp/dependencycheck/gradle/extension/NvdExtension.groovy
- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
> feat: Add support for startYear

- src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Counterpart for gradle-plugin of https://github.com/dependency-check/DependencyCheck/pull/7530
Fixes https://github.com/dependency-check/DependencyCheck/issues/7528 in the gradle plugin and adds the still missing CVSSv4 score to the failure threshold evaluations
> fix: Use unscored severity only in absence of any CVSS baseScore and add CVSSv4 score evaluation
