src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy
Hi, I recently started including the pugin in my builds and I'm finding a lot of false positives as multiple test paths are being included in the analysis.
Other than "test" we configure a bunch of other sourceSets for different types of tests (i.e. integrationTest, journeyTest, smokeTest, contractTest, androidTest...), for each of which gradle creates the -Runtime and -Compile configurations.
I believe that all of these configurations should be excluded from the analysis when the skipTestGroups is enabled.
This is a first attempt to expand on the exclusion issue based on my understanding of the industry consensus on naming alternative test sourceSets, any feedback on how to refine or expand it would be greatly appreciated.
=> expand the set of configurations recognized as test paths

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/integTest/resources/blacklistCustomConfiguration.gradle, src/integTest/resources/noSkipTestGroups.gradle, src/integTest/resources/scanCustomConfiguration.gradle, src/integTest/resources/skipCustomConfigurationViaWhitelist.gradle, src/integTest/resources/skipTestGroups.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/extension/CheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This commit adds two new properties to the `dependencyCheck` task:
`skipConfigurations` accepts a list of configuration names. The
dependencies of the named configurations are not analyzed. This does not
prevent the dependencies from being checked if other configurations
contain them as well - for example if other configurations extend the
named configurations.
`scanConfigurations` accepts a list of configuration names. Only the
dependencies of the named configurations will be analyzed.
`skipConfigurations` and `scanConfigurations` are mutually exclusive.
closes #6
=> provide more control over scanned configurations

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginIntegSpec.groovy, src/integTest/resources/outputDir.gradle, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This pull request adapts the unit test to #5.
The integration tests needed a bigger change as the plugin itself and the `outputDirectory` property had changed names. In addition the directory given as `outputDirectory` is created relative to the current working directory rather than the project's base directory so it was not where `fileExists` would expect it.
=> adapt tests to various code changes

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/integTest/resources/noSkipTestGroups.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/extension/CheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/tasks/CheckSpec.groovy
Let skipTestGroups check the inheritance hierarchy of a configuration to decide whether it is to be considered a test configuration
=> Test configuration detection is broken

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy
GradleException does not have a CTOR that takes only an exception/a throwable:
* [Javadoc (current)](https://docs.gradle.org/current/javadoc/org/gradle/api/GradleException.html)
* [Javadoc (v2.0)](https://docs.gradle.org/2.0/javadoc/org/gradle/api/GradleException.html)
* [Javadoc (v1.0)](https://docs.gradle.org/1.0/javadoc/org/gradle/api/GradleException.html)
=> Fix syntax error

build.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheck.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/CveExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Check.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Purge.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/tasks/CheckSpec.groovy
Defining the CHECK_TASK and CHECK_EXTENSION_NAME as the same value causes headaches when trying to invoke functionality typically available on Gradle Tasks e.g. doFirst {} or doLast {}.
```
// inside build.gradle...
dependencyCheck {
format = 'ALL'
}
// blows up with v.1.4.5
//dependencyCheck.doLast {
//    println 'in the doLast!!!!!!'
//}
// ugly workaround
tasks['dependencyCheck'].doLast {
println 'in the doLast!!!!!!'
}
```
Users of the plugin cannot gain direct access to the task because Gradle doesn't know if they are trying to reference the extension or the task (since both are the same name).  It seems when there's a conflict Gradle defaults to the extension.
The least invasive fix is provided in this pull request by creating a different name for the task while leaving the …
=> Differentiating extension name from task name

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPluginIntegSpec.groovy, src/integTest/resources/aggregateApp.gradle, src/integTest/resources/aggregateCore.gradle, src/integTest/resources/aggregateParent.gradle, src/integTest/resources/aggregateSettings.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This PR adds an aggregation task: `dependencyCheckAggregate`.
Note, this does not aggregate dependency check reports generated by `dependencyCheckAnalyze` (i.e. this is not a "merge" task). Rather this task will cycle threw all sub-projects from the root and run dependency check on them and write the results to a single report.
=> Add aggregate task per issue #13

build.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/utils/H2DBCleanupHook.groovy, src/main/resources/task.properties
Fixes issue with the custom h2 db lock file being left when the build is killed early. See https://github.com/jeremylong/DependencyCheck/pull/1030#issuecomment-352187395
Note - this also updates the data directory for gradle so that it should now consistently be located in: `~/.gradle/dependency-check-data/`.
=> Add Shutdown Hook

build.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Purge.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy
Resolves Issue #62 
When a dependency is scanned but no file type analyzer exists within the engine for the given dependency type a virtual dependency is used instead.
=> Fix Null Dependency

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy
Resolves Issue #71
To support multi-project android builds the new configurations.incomming API will now be used. However, one must now configure the types of dependencies that will be analyzed.  To that end a new property was added:
```groovy
dependencyCheck {
analyzedTypes = ['jar', 'aar', 'js', 'war', 'ear', 'zip']
}
```
The above is the default configuration (i.e. you do not need to specify this unless you want to add or remove types.
=> Enhance Multi-Project Support for Android

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Explicitly pass in the project reference otherwise projectName is always from the root project even if subproject is analyzing. It is confusing when enabling info level logger.
=> Subproject logging fix

src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
Hi @jeremylong 
We are trying to roll out the dependency check within the company. We thought it would be good if the plugin is able to exclude some subprojects while running dependencyCheckAggregate so that the resulting report only includes vulnerabilities for the projects that we care about.
Thanks very much for your consideration.
Regards,
Yun
=> Add the ability to exclude subprojects while running dependencyCheckAggregate.

src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DataExtension.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
Populate `DataExtension` from `project.gradle.gradleUserHomeDir`. 
See issue https://github.com/jeremylong/dependency-check-gradle/issues/136.
Added a test, however was not able to compare against the system property `user.home` as it is all temp paths in the unit test. For manual validation of this property being the correct one, see documentation, or try execute
```groovy
task('hello') {
doLast {
println project.gradle.gradleUserHomeDir
}
}
```
=> Configure default H2 database directory using gradleUserHome

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy
The current functionality is awkward in the following situation:
`root/foo` has dependencyCheckAggregate
`root` does not
`root/bar` does not
With that setup dependencyCheckAggregate would include `root` and `root/bar`, with this PR we check if the root project has the plugin, if not we just scan the projects below this one, meaning that `root/foo/bar` will be included but not `root/bar/cafe`
=> Only run dependencyCheckAggregate on rootproject if it has the plugin, otherwise use subprojects

src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy
If a downstream project was applying the plugin but not running the tasks,
they were suffering the overhead of configuring the tasks.
Changing to using tasks.register side-steps this.
=> Register tasks lazily

src/integTest/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/integTest/resources/skipGroups.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
This PR adds the ability to configure which dependency group prefixes should be skipped when scanning.
- Added `skipGroups` option to config
- Skips defined group prefixes when scanning
- Added integration test
- Extended unit tests
Limitation:
- I'm checking the group of the dependency on resolved artifact identifier which is:
- usable for standard external dependencies - id is e.g. `org.apache.logging.log4j:log4j-api:2.13.3` which can be skipped by e.g. `org.apache.logging` prefix
- not intuitive for internal dependencies from other subprojects in multi-project build - id is e.g. `project :my-module` which can be skipped by `project` prefix along with all internal dependencies
=> Fixes #132 : Add config option to skip dependency groups

README.md
Hello! Didn't find version 6.5.0 on [Maven central](https://mvnrepository.com/artifact/org.owasp/dependency-check-gradle)
=> Change dependency version to 6.5.0.1

src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Gradle 7.x removes testCompile in favor of testImplementation config.
This PR includes testImplementation in the determination of test config.
=> Include testImplementation in test determination

README.md, build.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPluginIntegSpec.groovy, src/test/resources/suppressions.xml
* Fixes issue #239 
* Improves performance on large gradle projects
The PR will likely fail due to lack of config for snapshot build dependencies.
=> Correct Use of Engine.scan()

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPluginIntegSpec.groovy
Currently, calling `dependencyCheckAnalyze` fails when Gradle configuration cache is enabled. In [Gradle 7.4](https://docs.gradle.org/7.4/release-notes.html#config-cache) there's a new option to declare the task as incompatible with configuration cache, so that the feature can be disabled when the task is invoked.
=> Call `notCompatibleWithConfigurationCache` when task doesn't support Gradle configuration cache

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Fixes #172
Use `project.buildFile` as opposed to pointing to the possibly wrong file when scanning.
=> Fix virtual path

src/main/groovy/org/owasp/dependencycheck/gradle/extension/OssIndexExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
Add option to specify OSS Index URL - useful for onprem mirrors/proxies in corporate environment.
Exposes functionality available in maven plugin by using the `<ossindexAnalyzerUrl>` parameter.
=> Add option to specify OSS Index URL

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Per #281 when `addInfoToDependencies` was updated one call was missed. This PR corrects the oversight and allows ODC to be used on older versions of gradle.
=> Fix support for old gradle versions

README.md, build.gradle, src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/ArtifactoryExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/CacheExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/CveExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DataExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/NodeAuditExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/OssIndexExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/ProxyExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/RetireJSExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/SlackExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/service/SlackNotificationSenderService.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Aggregate.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Analyze.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Purge.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/Update.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
Resolves #283
- Adds the ability to scan the `buildEnv`
- Adds the new `included by` references in the report to indicate the root parent dependencies that caused a transitive dependency to be included in the project. I.e. not the full dependency-tree - just the root.
=> feat: scan buildEnv

src/main/groovy/org/owasp/dependencycheck/gradle/extension/OssIndexExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
Allow gradle users to lesson the impact of hitting the OSS Index Rate Limit by configuring ODC to only produce warning messages instead of throwing an exception.
=> fix: add missing argument for OSS Index

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
As Gradle Project interface has groupId and version as java.lang.Object we should do as Gradle does and call toString() to get the string representation.
While fixing this I also spotted IntelliJ complaining about various parts where the included-by reference sets where use/modified as not all occurrences were updated when that changed from `Set<String>` to `Set<IncludedByReference>` so I fixed the occurrences of it in the AbstractAnalyze task as well.
=> fix: Could not find matching constructor... PackageURL for io.ehdev.version.Version after upgrade to 8.0.0

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Adds conversion support for ProjectComponentIdentifiers.
From the limited information available in a ProjectComponentIdentifier I considered the projectPath to be the most usable for generating a packageURL, but I'm open for modifications to what is used for the packageURL (I'm not too familiar with gradle, just enough to be able to code this fix)
=> fix: Gradle plugin breaking on ProjectComponentIdentifiers for multimodule projects

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
Fix for #315 
Resolves paths specified in `dependencyCheck.scanSet` using `project.file`. This reverts the scanSet property to the same behaviour as 7.4.0.
=> Fix groovy.lang.MissingMethodException when scanSet property is used (#315)

src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/NodePackageExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
Adds support for the skip dev dependencies flag from the Node Package analyzer.
=> Support ignoring dev dependencies in Node Package analyzer

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
The matchNonProxy method in the core utils library expects proxy.nonproxyhosts setting to be a pipe, comma, or semicolon delimited string, but the gradle plugin sets it as an array causing the values to be corrupted when they are read. Use a pipe delimited string instead.
resolves #319
=> fix: set proxy.nonproxyhosts setting as pipe delimited string

src/main/groovy/org/owasp/dependencycheck/gradle/extension/AdditionalCpe.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy, src/test/resources/scanAdditionalCpesConfiguration.gradle
This change allows adding CPEs to be included in analysis for dependencies that might not be picked up during scans.
For example to add in a dependency on PostgresSQL:
```
dependencyCheck {
additionalCpes {
postgreSql {
description = "PostgreSQL"
cpe = "cpe:2.3:a:postgresql:postgresql:${postgresqlVersion}:*:*:*:*:*:*:*"
}
}
}
```
=> Add the ability to manually specify addtional CPE entries to be checked.

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
=> fix: use match to identify test configuration

src/main/groovy/org/owasp/dependencycheck/gradle/extension/NvdExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy
Add the configurability of resultsPerPage from https://github.com/jeremylong/DependencyCheck/pull/6843 to the Gradle plugin
Prerequisite for successful build is an update to the version of DependencyCheck that has that PR integrated due to a dependency on the new Settings.KEYS value
=> feat: Allow configurable resultsPerPage in Gradle plugin

src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy
I guess it was a typo to use `==~` in the hierarchy check which will not find the intended configurations
as then the whole name would need to match. It should probably be `=~` which uses `find` just like in the
configuration name check right above.
=> fix: find regex in test configuration hierarchy check instead of match

src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy
=> Allow to use Action for configuration in extensions to better support non-Groovy consumers (#187)

README.md, gradle/libs.versions.toml, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy, src/test/resources/scanAdditionalCpesConfiguration.gradle
Somehow the gradle plugin was previously working without configuring the singleton `Downloader`:
```
Downloader.getInstance().configure(settings);
```
The other Maven plugins, Ant tasks, and the CLI all included the above call.
=> fix: resolve initialization problem using ODC-core 11.0.0

README.md
As ODC 11+ is no longer published to Maven Central the documentation needs to be updated.
=> docs: update examples to use the plugin portal instead of central

src/main/resources/task.properties
Gradle by default does not download the pom.xml from Central - without this false negatives may be generated.
resolves https://github.com/dependency-check/dependency-check-gradle/issues/421
=> fix: re-enable Central Analyzer by default

gradle/libs.versions.toml, src/main/groovy/org/owasp/dependencycheck/gradle/extension/AnalyzerExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/HostedSuppressionsExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/KEVExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/NvdExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/extension/RetireJSExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy
Implement bearer-authentication and add basic authentication options to onboard on the changes of https://github.com/jeremylong/DependencyCheck/pull/7277
* Extend NVD API datafeed authentication configuration with bearer
* Move KEV configuration to an extension
* Enable KEV mirror authentication configuration (both basic and bearer)
* Extend suppression files authentication configuration bearer
* Enable hostedSuppressions mirror authentication configuration (both basic and bearer)
* Enable RetireJS mirror authentication configuration(both basic and bearer)
Fixes https://github.com/jeremylong/DependencyCheck/issues/7131
=> feat: Extend authentication configuration options (including bearer)

src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy, src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckConfigurationSelectionIntegSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckGradlePluginSpec.groovy, src/test/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPluginIntegSpec.groovy, src/test/resources/aggregateParent.gradle, src/test/resources/blacklistCustomConfiguration.gradle, src/test/resources/noSkipTestGroups.gradle, src/test/resources/outputDir.gradle, src/test/resources/scanAdditionalCpesConfiguration.gradle, src/test/resources/scanCustomConfiguration.gradle, src/test/resources/skipCustomConfigurationViaWhitelist.gradle, src/test/resources/skipGroups.gradle, src/test/resources/skipTestGroups.gradle, src/test/resources/suppressionFiles.gradle, src/test/resources/suppressionFilesFailOnUnusedRule.gradle
fixes #429 
Adds support for https://github.com/jeremylong/DependencyCheck/pull/7244
=> feat: Add support for failBuildOnUnusedSuppressionRule
